export const CASE_DETAILS = 'CASE_DETAILS';
export const COUNTRIES_DETAILS='COUNTRIES_DETAILS';
export const NEWCASES_DETAILS= 'NEWCASES_DETAILS';
export const GRAPH_CASES = 'GRAPH_CASES';
export const NEWS_DETAILS='NEWS_DETAILS';
export const TWEETS_DETAILS='TWEETS_DETAILS';